In [1]:
import pandas as pd
import numpy as np

In [2]:
# Substitua este URL pelo URL 'raw' do seu arquivo CSV no GitHub
github_csv_url = 'https://github.com/dionequevedo/ia_para_devs/raw/refs/heads/main/data/brazilian_ecommerce/olist_order_items_dataset.csv'

try:
    df = pd.read_csv(github_csv_url)
    print("Dados importados com sucesso!")
    display(df.head())
except Exception as e:
    print(f"Ocorreu um erro ao importar os dados: {e}")
    print("Por favor, verifique se o URL está correto e se o arquivo CSV é acessível.")

Dados importados com sucesso!

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [36]:
result = df.loc[df['product_id']=='7634da152a4610f1595efa32f14722fc', 'price']
print(result)

#define um indice para o dataFrame
#df.set_index('product_id')
result2 = df.loc[df['product_id']=='7634da152a4610f1595efa32f14722fc', 'price']
print(result2)

3        12.99
83328    12.99
Name: price, dtype: float64

In [37]:
vazios = df.isna().sum()
print(vazios)

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [3]:
num_rows = df.shape[0]
print(f"O DataFrame contém {num_rows} linhas.")
print("--------------------------------------")
print("Cabeçalhos das colunas:")
display(df.columns.tolist())

O DataFrame contém 112650 linhas.
--------------------------------------
Cabeçalhos das colunas:

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value']

In [4]:
# Substitua este URL pelo URL 'raw' do seu arquivo CSV no GitHub
new_github_csv_url = 'https://github.com/dionequevedo/ia_para_devs/raw/refs/heads/main/data/brazilian_ecommerce/olist_products_dataset.csv'

try:
    df_product = pd.read_csv(new_github_csv_url)
    print("Dados importados com sucesso!")
    display(df_product.head())
except Exception as e:
    print(f"Ocorreu um erro ao importar os dados: {e}")
    print("Por favor, verifique se o URL está correto e se o arquivo CSV é acessível.")

Dados importados com sucesso!

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [5]:
# Informa o total de linhas importadas
num_rows = df_product.shape[0]
print(f"O DataFrame contém {num_rows} linhas.")
print("--------------------------------------")
# Lista os cabeçalhos disponíveis para trabalho
print("Cabeçalhos das colunas:")
display(df_product.columns.tolist())

O DataFrame contém 32951 linhas.
--------------------------------------
Cabeçalhos das colunas:

['product_id',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [15]:
category_40_more = df_product.loc[df_product['product_name_lenght'] >= 40, 'product_category_name']
print(category_40_more)

list_0_to_4 = df_product.iloc[0:5, 1:3]
print(list_0_to_4)

0                               perfumaria
1                                    artes
2                            esporte_lazer
5                    instrumentos_musicais
6                               cool_stuff
                       ...
32946                     moveis_decoracao
32947    construcao_ferramentas_iluminacao
32948                      cama_mesa_banho
32949               informatica_acessorios
32950                      cama_mesa_banho
Name: product_category_name, Length: 25924, dtype: str
   product_category_name  product_name_lenght
0             perfumaria                 40.0
1                  artes                 44.0
2          esporte_lazer                 46.0
3                  bebes                 27.0
4  utilidades_domesticas                 37.0